"""initial

Revision ID: ea5ccfc6f4ae
Revises: 
Create Date: 2026-06-30 19:43:48.196690
"""
from __future__ import annotations

from typing import Collection, Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ea5ccfc6f4ae'
down_revision: str | None = None
branch_labels: str | Collection[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
